#pragma once

#include <Anggur/Helper/Enum.hpp>
#include "Event.hpp"

namespace Anggur {

#define Anggur_ScancodeMask (1 << 30)
#define Anggur_ScancodeLength 512

enum class Key : int
{
    Unknown = 0,

    Return      = 40,
    Escape      = 41,
    Backspace   = 42,
    Tab         = 43,
    Space       = 44,
    Minus       = 45,
    Equals      = 46,
    LBracket    = 47,
    RBracket    = 48,
    Backslash   = 49,
    NonUsHash   = 50, // Euro
    Semicolon   = 51,
    Quote       = 52,
    Backtick    = 53,
    Comma       = 54,
    Period      = 55,
    Slash       = 56,

    N1 = 30,
    N2 = 31,
    N3 = 32,
    N4 = 33,
    N5 = 34,
    N6 = 35,
    N7 = 36,
    N8 = 37,
    N9 = 38,
    N0 = 39,

    A = 4,
    B = 5,
    C = 6,
    D = 7,
    E = 8,
    F = 9,
    G = 10,
    H = 11,
    I = 12,
    J = 13,
    K = 14,
    L = 15,
    M = 16,
    N = 17,
    O = 18,
    P = 19,
    Q = 20,
    R = 21,
    S = 22,
    T = 23,
    U = 24,
    V = 25,
    W = 26,
    X = 27,
    Y = 28,
    Z = 29,

    CapsLock = 57,

    F1  = 58,
    F2  = 59,
    F3  = 60,
    F4  = 61,
    F5  = 62,
    F6  = 63,
    F7  = 64,
    F8  = 65,
    F9  = 66,
    F10 = 67,
    F11 = 68,
    F12 = 69,

    PrintScreen = 70,
    ScrollLock  = 71,
    Pause       = 72,
    Insert      = 73,
    Home        = 74,
    PageUp      = 75,
    Delete      = 76,
    End         = 77,
    PageDown    = 78,
    Right       = 79,
    Left        = 80,
    Down        = 81,
    Up          = 82,

    PadNumLock = 83,

    PadDivide   = 84,
    PadMultiply = 85,
    PadMinus    = 86,
    PadPlus     = 87,
    PadReturn   = 88,
    PadPoint    = 99,
    PadComma    = 133,
    PadEqual    = 103,
    PadEqual400 = 134,

    Pad1 = 89,
    Pad2 = 90,
    Pad3 = 91,
    Pad4 = 92,
    Pad5 = 93,
    Pad6 = 94,
    Pad7 = 95,
    Pad8 = 96,
    Pad9 = 97,
    Pad0 = 98,

    Application = 101,
    Power       = 102,

    F13 = 104,
    F14 = 105,
    F15 = 106,
    F16 = 107,
    F17 = 108,
    F18 = 109,
    F19 = 110,
    F20 = 111,
    F21 = 112,
    F22 = 113,
    F23 = 114,
    F24 = 115,

    Execute     = 116,
    Help        = 117,
    Menu        = 118,
    Select      = 119,
    Stop        = 120,
    Redo        = 121,
    Undo        = 122,
    Cut         = 123,
    Copy        = 124,
    Paste       = 125,
    Find        = 126,
    Mute        = 127,
    VolumeUp    = 128,
    VolumeDown  = 129,


    AltErase   = 153,
    SysReq     = 154,
    Cancel     = 155,
    Clear      = 156,
    Prior      = 157,
    Return2    = 158,
    Separator  = 159,
    Out        = 160,
    Oper       = 161,
    ClearAgain = 162,
    Crsel      = 163,
    Exsel      = 164,

    ThousandsSeparator = 178,
    DecimalSeparator   = 179,
    CurrencyUnit       = 180,
    CurrencySubunit    = 181,

    Pad00              = 176,
    Pad000             = 177,
    PadLParen          = 182,
    PadRParen          = 183,
    PadLBrace          = 184,
    PadRBrace          = 185,
    PadTab             = 186,
    PadBackspace       = 187,
    PadA               = 188,
    PadB               = 189,
    PadC               = 190,
    PadD               = 191,
    PadE               = 192,
    PadF               = 193,
    PadXor             = 194,
    PadPower           = 195,
    PadPercent         = 196,
    PadLess            = 197,
    PadGreater         = 198,
    PadAmpersand       = 199,
    PadDoubleAmpersand = 200,
    PadVertBar         = 201,
    PadDoubleVertBar   = 202,
    PadColon           = 203,
    PadHash            = 204,
    PadSpace           = 205,
    PadAt              = 206,
    PadExclam          = 207,
    PadMemStore        = 208,
    PadMemRecall       = 209,
    PadMemClear        = 210,
    PadMemAdd          = 211,
    PadMemSubtract     = 212,
    PadMemMultiply     = 213,
    PadMemDivide       = 214,
    PadPlusMinus       = 215,
    PadClear           = 216,
    PadClearEntry      = 217,
    PadBinary          = 218,
    PadOctal           = 219,
    PadDecimal         = 220,
    PadHexadecimal     = 221,

    LControl = 224,
    LShift   = 225,
    LAlt     = 226,
    LMeta    = 227,
    RControl = 228,
    RShift   = 229,
    RAlt     = 230,
    RMeta    = 231,

    AltGr = 257,

    AudioNext = 258,
    AudioPrev = 259,
    AudioStop = 260,
    AudioPlay = 261,
    AudioMute = 262,

    AudioRewind      = 285,
    AudioFastForward = 286,

    MediaSelect = 263,
    Www         = 264,
    Mail        = 265,
    Calculator  = 266,
    Computer    = 267,
    AcSearch    = 268,
    AcHome      = 269,
    AcBack      = 270,
    AcForward   = 271,
    AcStop      = 272,
    AcRefresh   = 273,
    AcBookmarks = 274,

    BrightnessDown = 275,
    BrightnessUp   = 276,
    DisplaySwitch  = 277,
    IllumToggle    = 278,
    IllumDown      = 279,
    IllumUp        = 280,

    Eject = 281,
    Sleep = 282,
    App1  = 283,
    App2  = 284,
};

enum class KeyVir: int
{
    Unknown = 0,

    Return      = '\r',
    Escape      = '\033',
    Backspace   = '\b',
    Tab         = '\t',
    Space       = ' ',
    Exclam      = '!',
    DoubleQuote = '"',
    Hash        = '#',
    Percent     = '%',
    Dollar      = '$',
    Ampersand   = '&',
    Quote       = '\'',
    LParen      = '(',
    RParen      = ')',
    Asterisk    = '*',
    Plus        = '+',
    Comma       = ',',
    Minus       = '-',
    Period      = '.',
    Slash       = '/',

    N0 = '0',
    N1 = '1',
    N2 = '2',
    N3 = '3',
    N4 = '4',
    N5 = '5',
    N6 = '6',
    N7 = '7',
    N8 = '8',
    N9 = '9',

    Colon     = ':',
    Semicolon = ';',
    Less      = '<',
    Equals    = '=',
    Greater   = '>',
    Question  = '?',
    At        = '@',

    LBracket   = '[',
    RBracket   = ']',
    Backslash  = '\\',
    Caret      = '^',
    Underscore = '_',
    Backtick   = '`',

    A = 'a',
    B = 'b',
    C = 'c',
    D = 'd',
    E = 'e',
    F = 'f',
    G = 'g',
    H = 'h',
    I = 'i',
    J = 'j',
    K = 'k',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    P = 'p',
    Q = 'q',
    R = 'r',
    S = 's',
    T = 't',
    U = 'u',
    V = 'v',
    W = 'w',
    X = 'x',
    Y = 'y',
    Z = 'z',

    CapsLock = (Anggur_ScancodeMask|57),

    F1  = (Anggur_ScancodeMask|58),
    F2  = (Anggur_ScancodeMask|59),
    F3  = (Anggur_ScancodeMask|60),
    F4  = (Anggur_ScancodeMask|61),
    F5  = (Anggur_ScancodeMask|62),
    F6  = (Anggur_ScancodeMask|63),
    F7  = (Anggur_ScancodeMask|64),
    F8  = (Anggur_ScancodeMask|65),
    F9  = (Anggur_ScancodeMask|66),
    F10 = (Anggur_ScancodeMask|67),
    F11 = (Anggur_ScancodeMask|68),
    F12 = (Anggur_ScancodeMask|69),

    PrintScreen = (Anggur_ScancodeMask|70),
    ScrollLock  = (Anggur_ScancodeMask|71),
    Pause       = (Anggur_ScancodeMask|72),
    Insert      = (Anggur_ScancodeMask|73),
    Home        = (Anggur_ScancodeMask|74),
    PageUp      = (Anggur_ScancodeMask|75),
    Delete      = '\177',
    End         = (Anggur_ScancodeMask|77),
    PageDown    = (Anggur_ScancodeMask|78),
    Right       = (Anggur_ScancodeMask|79),
    Left        = (Anggur_ScancodeMask|80),
    Down        = (Anggur_ScancodeMask|81),
    Up          = (Anggur_ScancodeMask|82),

    PadNumLock = (Anggur_ScancodeMask|83),

    PadDivide   = (Anggur_ScancodeMask|84),
    PadMultiply = (Anggur_ScancodeMask|85),
    PadMinus    = (Anggur_ScancodeMask|86),
    PadPlus     = (Anggur_ScancodeMask|87),
    PadReturn   = (Anggur_ScancodeMask|88),
    PadPoint    = (Anggur_ScancodeMask|99),
    PadComma    = (Anggur_ScancodeMask|133),
    PadEqual    = (Anggur_ScancodeMask|103),
    PadEqual400 = (Anggur_ScancodeMask|134),

    Pad1 = (Anggur_ScancodeMask|89),
    Pad2 = (Anggur_ScancodeMask|90),
    Pad3 = (Anggur_ScancodeMask|91),
    Pad4 = (Anggur_ScancodeMask|92),
    Pad5 = (Anggur_ScancodeMask|93),
    Pad6 = (Anggur_ScancodeMask|94),
    Pad7 = (Anggur_ScancodeMask|95),
    Pad8 = (Anggur_ScancodeMask|96),
    Pad9 = (Anggur_ScancodeMask|97),
    Pad0 = (Anggur_ScancodeMask|98),

    Application = (Anggur_ScancodeMask|101),
    Power       = (Anggur_ScancodeMask|102),

    F13 = (Anggur_ScancodeMask|104),
    F14 = (Anggur_ScancodeMask|105),
    F15 = (Anggur_ScancodeMask|106),
    F16 = (Anggur_ScancodeMask|107),
    F17 = (Anggur_ScancodeMask|108),
    F18 = (Anggur_ScancodeMask|109),
    F19 = (Anggur_ScancodeMask|110),
    F20 = (Anggur_ScancodeMask|111),
    F21 = (Anggur_ScancodeMask|112),
    F22 = (Anggur_ScancodeMask|113),
    F23 = (Anggur_ScancodeMask|114),
    F24 = (Anggur_ScancodeMask|115),

    Execute     = (Anggur_ScancodeMask|116),
    Help        = (Anggur_ScancodeMask|117),
    Menu        = (Anggur_ScancodeMask|118),
    Select      = (Anggur_ScancodeMask|119),
    Stop        = (Anggur_ScancodeMask|120),
    Redo        = (Anggur_ScancodeMask|121),
    Undo        = (Anggur_ScancodeMask|122),
    Cut         = (Anggur_ScancodeMask|123),
    Copy        = (Anggur_ScancodeMask|124),
    Paste       = (Anggur_ScancodeMask|125),
    Find        = (Anggur_ScancodeMask|126),
    Mute        = (Anggur_ScancodeMask|127),
    VolumeUp    = (Anggur_ScancodeMask|128),
    VolumeDown  = (Anggur_ScancodeMask|129),


    AltErase   = (Anggur_ScancodeMask|153),
    SysReq     = (Anggur_ScancodeMask|154),
    Cancel     = (Anggur_ScancodeMask|155),
    Clear      = (Anggur_ScancodeMask|156),
    Prior      = (Anggur_ScancodeMask|157),
    Return2    = (Anggur_ScancodeMask|158),
    Separator  = (Anggur_ScancodeMask|159),
    Out        = (Anggur_ScancodeMask|160),
    Oper       = (Anggur_ScancodeMask|161),
    ClearAgain = (Anggur_ScancodeMask|162),
    Crsel      = (Anggur_ScancodeMask|163),
    Exsel      = (Anggur_ScancodeMask|164),

    ThousandsSeparator = (Anggur_ScancodeMask|178),
    DecimalSeparator   = (Anggur_ScancodeMask|179),
    CurrencyUnit       = (Anggur_ScancodeMask|180),
    CurrencySubunit    = (Anggur_ScancodeMask|181),

    Pad00              = (Anggur_ScancodeMask|176),
    Pad000             = (Anggur_ScancodeMask|177),
    PadLParen          = (Anggur_ScancodeMask|182),
    PadRParen          = (Anggur_ScancodeMask|183),
    PadLBrace          = (Anggur_ScancodeMask|184),
    PadRBrace          = (Anggur_ScancodeMask|185),
    PadTab             = (Anggur_ScancodeMask|186),
    PadBackspace       = (Anggur_ScancodeMask|187),
    PadA               = (Anggur_ScancodeMask|188),
    PadB               = (Anggur_ScancodeMask|189),
    PadC               = (Anggur_ScancodeMask|190),
    PadD               = (Anggur_ScancodeMask|191),
    PadE               = (Anggur_ScancodeMask|192),
    PadF               = (Anggur_ScancodeMask|193),
    PadXor             = (Anggur_ScancodeMask|194),
    PadPower           = (Anggur_ScancodeMask|195),
    PadPercent         = (Anggur_ScancodeMask|196),
    PadLess            = (Anggur_ScancodeMask|197),
    PadGreater         = (Anggur_ScancodeMask|198),
    PadAmpersand       = (Anggur_ScancodeMask|199),
    PadDoubleAmpersand = (Anggur_ScancodeMask|200),
    PadVertBar         = (Anggur_ScancodeMask|201),
    PadDoubleVertBar   = (Anggur_ScancodeMask|202),
    PadColon           = (Anggur_ScancodeMask|203),
    PadHash            = (Anggur_ScancodeMask|204),
    PadSpace           = (Anggur_ScancodeMask|205),
    PadAt              = (Anggur_ScancodeMask|206),
    PadExclam          = (Anggur_ScancodeMask|207),
    PadMemStore        = (Anggur_ScancodeMask|208),
    PadMemRecall       = (Anggur_ScancodeMask|209),
    PadMemClear        = (Anggur_ScancodeMask|210),
    PadMemAdd          = (Anggur_ScancodeMask|211),
    PadMemSubtract     = (Anggur_ScancodeMask|212),
    PadMemMultiply     = (Anggur_ScancodeMask|213),
    PadMemDivide       = (Anggur_ScancodeMask|214),
    PadPlusMinus       = (Anggur_ScancodeMask|215),
    PadClear           = (Anggur_ScancodeMask|216),
    PadClearEntry      = (Anggur_ScancodeMask|217),
    PadBinary          = (Anggur_ScancodeMask|218),
    PadOctal           = (Anggur_ScancodeMask|219),
    PadDecimal         = (Anggur_ScancodeMask|220),
    PadHexadecimal     = (Anggur_ScancodeMask|221),

    LControl = (Anggur_ScancodeMask|224),
    LShift   = (Anggur_ScancodeMask|225),
    LAlt     = (Anggur_ScancodeMask|226),
    LMeta    = (Anggur_ScancodeMask|227),
    RControl = (Anggur_ScancodeMask|228),
    RShift   = (Anggur_ScancodeMask|229),
    RAlt     = (Anggur_ScancodeMask|230),
    RMeta    = (Anggur_ScancodeMask|231),

    AltGr = (Anggur_ScancodeMask|257),

    AudioNext = (Anggur_ScancodeMask|258),
    AudioPrev = (Anggur_ScancodeMask|259),
    AudioStop = (Anggur_ScancodeMask|260),
    AudioPlay = (Anggur_ScancodeMask|261),
    AudioMute = (Anggur_ScancodeMask|262),

    AudioRewind      = (Anggur_ScancodeMask|285),
    AudioFastForward = (Anggur_ScancodeMask|286),

    MediaSelect = (Anggur_ScancodeMask|263),
    Www         = (Anggur_ScancodeMask|264),
    Mail        = (Anggur_ScancodeMask|265),
    Calculator  = (Anggur_ScancodeMask|266),
    Computer    = (Anggur_ScancodeMask|267),
    AcSearch    = (Anggur_ScancodeMask|268),
    AcHome      = (Anggur_ScancodeMask|269),
    AcBack      = (Anggur_ScancodeMask|270),
    AcForward   = (Anggur_ScancodeMask|271),
    AcStop      = (Anggur_ScancodeMask|272),
    AcRefresh   = (Anggur_ScancodeMask|273),
    AcBookmarks = (Anggur_ScancodeMask|274),

    BrightnessDown = (Anggur_ScancodeMask|275),
    BrightnessUp   = (Anggur_ScancodeMask|276),
    DisplaySwitch  = (Anggur_ScancodeMask|277),
    IllumToggle    = (Anggur_ScancodeMask|278),
    IllumDown      = (Anggur_ScancodeMask|279),
    IllumUp        = (Anggur_ScancodeMask|280),

    Eject = (Anggur_ScancodeMask|281),
    Sleep = (Anggur_ScancodeMask|282),
    App1  = (Anggur_ScancodeMask|283),
    App2  = (Anggur_ScancodeMask|284),
};

enum class KeyMod : unsigned int
{
    None     = 0x0000,
    LShift   = 0x0001,
    RShift   = 0x0002,
    Shift    = 0x0001|0x0002,
    LControl = 0x0040,
    RControl = 0x0080,
    Control  = 0x0040|0x0080,
    LAlt     = 0x0100,
    RAlt     = 0x0200,
    Alt      = 0x0100|0x0200,
    LMeta    = 0x0400,
    RMeta    = 0x0800,
    Meta     = 0x0400|0x0800,
    NumLock  = 0x1000,
    CapsLock = 0x2000,
    AltGr    = 0x4000,
    Reseved  = 0x8000
};

Anggur_EnumOverloads(KeyMod);

}
