sources:
  - src/context.c
  - src/init.c
  - src/input.c
  - src/monitor.c
  - src/vulkan.c
  - src/window.c

platforms:
  linux:
    sources:
      - src/x11_init.c
      - src/x11_monitor.c
      - src/x11_window.c
      - src/xkb_unicode.c
      - src/posix_time.c
      - src/posix_thread.c
      - src/glx_context.c
      - src/egl_context.c
      - src/osmesa_context.c
      - src/linux_joystick.c
  osx:
    sources:
      - src/cocoa_init.c
      - src/cocoa_monitor.c
      - src/cocoa_window.c
      - src/cocoa_unicode.c
      - src/cocoa_time.c
      - src/cocoa_thread.c
      - src/cocoa_context.c
      - src/cocoa_context.c
      - src/cocoa_context.c
      - src/cocoa_joystick.c
  windows:
    sources:
      - src/win32_init.c
      - src/win32_joystick.c
      - src/win32_monitor.c
      - src/win32_time.c
      - src/win32_thread.c
      - src/win32_window.c
      - src/wgl_context.c
      - src/egl_context.c
      - src/osmesa_context.c
